services:
  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: RETURN
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 43910208
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: .
    container_name: parking-app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/RETURN
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 43910208
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  postgres-data: